server:
  port: 8500

spring:
  application:
    name: 03-lesson

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.2.100:5432/pract?currentSchema=market
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver



