server:
  port: 8500

spring:
  application:
    name: 03-lesson
  servlet:
    multipart:
      max-file-size: 20480 KB

  web:
    resources:
      static-locations:  classpath:./static,file:C:/opt/market/,file:C:/opt/market/images/
#      static-locations: classpath:./static

#      static-locations: classpath:file:./static/ C:/opt/market/
#  mvc:
#    static-path-pattern: /**

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.2.100:5432/pract?currentSchema=market
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver



