server:
  port: 8501

spring:
  application:
    name: 03-lesson
  servlet:
    multipart:
      max-file-size: 20480 KB

  web:
    resources:
      static-locations: classpath:./static,file:C:/opt/market/,file:C:/opt/market/images/
  mvc:
    static-path-pattern: /**

  data:
    redis:
      port: 6379
      host: 192.168.0.200
  cache:
    redis:
      time-to-live: PT30M

  r2dbc:
    url: r2dbc:postgresql://192.168.0.200:5432/pract?currentSchema=market   # URL подключения к базе данных
    username: postgres                              # Имя пользователя базы данных
    password: 123                          # Пароль пользователя
    #    pool:
    #      enabled: true                               # Включение пула соединений
    #      initial-size: 10                            # Начальное количество соединений в пуле
    #      max-size: 50                                # Максимальное количество соединений
    #      max-idle-time: 50s                          # Время бездействия соединения перед закрытием
    #      max-life-time: 10m                          # Максимальное время жизни соединения
    #      validation-query: SELECT 1                  # SQL-запрос для проверки

    logging:
      level:
        org.springframework.r2dbc.core.DefaultDatabaseClient: DEBUG # заодно включим логирование SQL-запросов
        io.r2dbc: DEBUG # и добавим больше деталей (не включать в настоящем приложении)


management:
  endpoints:
    health.probes.enabled: true
    health.show-details: always
    health:
      group:
        readiness:
          include=readinessState,indicator: true
          show-details: always

    web:
      exposure:
        include: mappings

order-key: 'order:payment'
remote-server: 'http://localhost:8502'