server:
  port: 8502

spring:
  application:
    name: payments

  data:
    redis:
      port: 6379
      host: 192.168.2.100
  cache:
    redis:
      time-to-live: PT1H



  r2dbc:
    url: r2dbc:postgresql://192.168.2.100:5432/pract?currentSchema=market   # URL подключения к базе данных
    username: postgres                              # Имя пользователя базы данных
    password: 123                          # Пароль пользователя
    #    pool:
    #      enabled: true                               # Включение пула соединений
    #      initial-size: 10                            # Начальное количество соединений в пуле
    #      max-size: 50                                # Максимальное количество соединений
    #      max-idle-time: 50s                          # Время бездействия соединения перед закрытием
    #      max-life-time: 10m                          # Максимальное время жизни соединения
    #      validation-query: SELECT 1                  # SQL-запрос для проверки





springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    enabled: true
    path: /swagger/index.html

management:
  endpoints:
    health.probes.enabled: true
    health.show-details: always
    health:
      group:
        readiness:
          include=readinessState,indicator: true
          show-details: always

    web:
      exposure:
        include: mappings

